apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rsenvcomp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rs-demos-jeyt-tenant/rsenvapp/rsenvcomp@sha256:2f3232b8d802bda26d86c117651ce108d023c2f33003f97d264fbea37d4ec31f
        name: my-java-quarkus
        resources: {}
status: {}
